import type { Metadata } from "next";
import "../global.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import QueryClientProviderComponent from "@/app/QueryClientProviderComponent";

export const metadata: Metadata = {
	title: "Hono | nextjs",
	description: "Generated by hono",
};

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={plusJakartaSans.className}>
			<body>
				<QueryClientProviderComponent>{children}</QueryClientProviderComponent>
			</body>
		</html>
	);
}
